[../include/]amiga39/fd/amigaguide_lib.fd		+amiga39
[../include/]amiga39/fd/aml_lib.fd		+amiga39
[../include/]amiga39/fd/arexx_lib.fd		+amiga39
[../include/]amiga39/fd/asl_lib.fd		+amiga39
[../include/]amiga39/fd/battclock_lib.fd		+amiga39
[../include/]amiga39/fd/battmem_lib.fd		+amiga39
[../include/]amiga39/fd/bevel_lib.fd		+amiga39
[../include/]amiga39/fd/bitmap_lib.fd		+amiga39
[../include/]amiga39/fd/bullet_lib.fd		+amiga39
[../include/]amiga39/fd/button_lib.fd		+amiga39
[../include/]amiga39/fd/cardres_lib.fd		+amiga39
[../include/]amiga39/fd/checkbox_lib.fd		+amiga39
[../include/]amiga39/fd/chooser_lib.fd		+amiga39
[../include/]amiga39/fd/cia_lib.fd		+amiga39
[../include/]amiga39/fd/clicktab_lib.fd		+amiga39
[../include/]amiga39/fd/colorwheel_lib.fd		+amiga39
[../include/]amiga39/fd/commodities_lib.fd		+amiga39
[../include/]amiga39/fd/console_lib.fd		+amiga39
[../include/]amiga39/fd/datatypes_lib.fd		+amiga39
[../include/]amiga39/fd/datebrowser_lib.fd		+amiga39
[../include/]amiga39/fd/diskfont_lib.fd		+amiga39
[../include/]amiga39/fd/dos_lib.fd		+amiga39
[../include/]amiga39/fd/drawlist_lib.fd		+amiga39
[../include/]amiga39/fd/dtclass_lib.fd		+amiga39
[../include/]amiga39/fd/exec_lib.fd		+amiga39
[../include/]amiga39/fd/expansion_lib.fd		+amiga39
[../include/]amiga39/fd/fuelgauge_lib.fd		+amiga39
[../include/]amiga39/fd/gadtools_lib.fd		+amiga39
[../include/]amiga39/fd/getfile_lib.fd		+amiga39
[../include/]amiga39/fd/getfont_lib.fd		+amiga39
[../include/]amiga39/fd/getscreenmode_lib.fd		+amiga39
[../include/]amiga39/fd/glyph_lib.fd		+amiga39
[../include/]amiga39/fd/graphics_lib.fd		+amiga39
[../include/]amiga39/fd/hdwrench.fd		+amiga39
[../include/]amiga39/fd/icon_lib.fd		+amiga39
[../include/]amiga39/fd/iffparse_lib.fd		+amiga39
[../include/]amiga39/fd/input_lib.fd		+amiga39
[../include/]amiga39/fd/integer_lib.fd		+amiga39
[../include/]amiga39/fd/intuition_lib.fd		+amiga39
[../include/]amiga39/fd/keymap_lib.fd		+amiga39
[../include/]amiga39/fd/label_lib.fd		+amiga39
[../include/]amiga39/fd/layers_lib.fd		+amiga39
[../include/]amiga39/fd/layout_lib.fd		+amiga39
[../include/]amiga39/fd/listbrowser_lib.fd		+amiga39
[../include/]amiga39/fd/locale_lib.fd		+amiga39
[../include/]amiga39/fd/lowlevel_lib.fd		+amiga39
[../include/]amiga39/fd/mathffp_lib.fd		+amiga39
[../include/]amiga39/fd/mathieeedoubbas_lib.fd		+amiga39
[../include/]amiga39/fd/mathieeedoubtrans_lib.fd		+amiga39
[../include/]amiga39/fd/mathieeesingbas_lib.fd		+amiga39
[../include/]amiga39/fd/mathieeesingtrans_lib.fd		+amiga39
[../include/]amiga39/fd/mathtrans_lib.fd		+amiga39
[../include/]amiga39/fd/misc_lib.fd		+amiga39
[../include/]amiga39/fd/nonvolatile_lib.fd		+amiga39
[../include/]amiga39/fd/palette_lib.fd		+amiga39
[../include/]amiga39/fd/penmap_lib.fd		+amiga39
[../include/]amiga39/fd/popcycle_lib.fd		+amiga39
[../include/]amiga39/fd/potgo_lib.fd		+amiga39
[../include/]amiga39/fd/radiobutton_lib.fd		+amiga39
[../include/]amiga39/fd/ramdrive_lib.fd		+amiga39
[../include/]amiga39/fd/realtime_lib.fd		+amiga39
[../include/]amiga39/fd/requester_lib.fd		+amiga39
[../include/]amiga39/fd/resource_lib.fd		+amiga39
[../include/]amiga39/fd/scroller_lib.fd		+amiga39
[../include/]amiga39/fd/slider_lib.fd		+amiga39
[../include/]amiga39/fd/space_lib.fd		+amiga39
[../include/]amiga39/fd/speedbar_lib.fd		+amiga39
[../include/]amiga39/fd/string_lib.fd		+amiga39
[../include/]amiga39/fd/texteditor_lib.fd		+amiga39
[../include/]amiga39/fd/timer_lib.fd		+amiga39
[../include/]amiga39/fd/translator_lib.fd		+amiga39
[../include/]amiga39/fd/utility_lib.fd		+amiga39
[../include/]amiga39/fd/virtual_lib.fd		+amiga39
[../include/]amiga39/fd/wb_lib.fd		+amiga39
[../include/]amiga39/fd/window_lib.fd		+amiga39
[../include/]amiga39/fd/disk_lib.fd		+amiga39
[../include/]amiga39/fd/rexxsyslib_lib.fd		+amiga39
